### PR TITLE
updated linux build instructions from my attempt to build

### PR DESCRIPTION
**Pull request by olldray**

### CODE REVIEW

**Comment by danlyke** [comment]
Awesome! Thank you for the notes, you are now the 3rd submitter to the project!

**Comment by olldray** [comment]
.... I think it is possible that you meant to merge it, rather than close it. :-P

**Comment by mpogue2** [comment]
Hmmm...I've never done this, and I do see that the change is not merged yet...let's try reopening!

**Comment by mpogue2** [comment]
Rebased it to Master....looks like it worked...

**Comment by danlyke** [comment]
Yay! Thanks, Mike, that's what I meant to do, I just clicked the wrong thing, apparently (I usually do this from the command-lne).

**Pull request merged**
